# Links de navegação principal
main:
  - name: Início
    url: /
    weight: 10
  - name: Perfil
    url: /perfil/
    weight: 20
  - name: Publicações
    url: /publication/
    weight: 30
  - name: Eventos
    url: /events/
    weight: 35
  - name: Notícias
    url: /post/
    weight: 40
  - name: Vídeos
    url: /videos/
    weight: 50
  - name: Podcast
    url: /podcast/
    weight: 60
  - name: Material Didático
    url: /materiais/
    weight: 70
  - name: Grupo de Pesquisa
    url: /projects/
    weight: 80
  - name: Consultoria Jurídica
    url: /advocacia/
    weight: 85
  - name: Contato
    url: /contato/
    weight: 90
