# Links de navegação principal
main:
  - name: Início
    url: /
    weight: 10
  - name: Publicações
    url: /publication/
    weight: 20
  - name: Notícias
    url: /post/
    weight: 30
  - name: Vídeos
    url: /videos/
    weight: 40
  - name: Podcast
    url: /podcast/
    weight: 50
  - name: Materiais Didáticos
    url: /materiais/
    weight: 60
  - name: Projetos de Pesquisa
    url: /projects/
    weight: 70
